# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Oscar Pindaro
email: oscar.pindaro@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Mega blog super pazzo in cui scrivo quello che voglio
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://oscarpindaro.github.io"
github_username:  OscarPindaro


markdown: kramdown
kramdown:
  math_engine: katex


# Build settings
theme: minima
plugins:
  - jekyll-feed # geenrates the rss feed
  - jekyll-tabs # for generating tabs with different text in it
  - jekyll-imagemagick # for responsive images of different sizes

imagemagick:
  enabled: false# enables responsive images for your site (recommended, see https://github.com/alshedivat/al-folio/issues/537)
  widths:
    - 480
    - 800
    - 1400
  input_directories:
    - assets/img/
    # - assets/gif/
  input_formats:
    - '.jpg'
    - '.jpeg'
    - '.png'
    - '.tiff'
    # - '.gif'
  output_formats:
    webp: '-quality 85'


# this loads the images only when they are met while scrolling
lazy_loading_images: true

# Collections
collections:
  pensierini:
    output: false
    permalink: /pensierini/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pensierini"
    values:
      layout: null
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

sass:
  quiet_deps: true
  silence_deprecations:
    - import

# this pages will appear in the nav bar
# the pages MUST have a title
header_pages:
  - index.markdown
  - pensierini.markdown

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .venv
  - .pre-commit-config.yaml

# some general configuration infos
timezone: Europe/Rome
